apiVersion: v1
kind: Service
metadata:
  name: mongodb-service-0
  namespace: default
spec:
  selector:
    app: mongodb
    statefulset.kubernetes.io/pod-name: mongodb-0
  type: NodePort
  ports:
   - protocol: TCP
     port: 27017
     targetPort: 27017
     nodePort: 32717
  externalIPs:
   - 192.168.0.20
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service-1
  namespace: default
spec:
  selector:
    app: mongodb
    statefulset.kubernetes.io/pod-name: mongodb-1
  type: NodePort
  ports:
   - protocol: TCP
     port: 27017
     targetPort: 27017
     nodePort: 32718
  externalIPs:
   - 192.168.0.21
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service-2
  namespace: default
spec:
  selector:
    app: mongodb
    statefulset.kubernetes.io/pod-name: mongodb-2
  type: NodePort
  ports:
   - protocol: TCP
     port: 27017
     targetPort: 27017
     nodePort: 32719
  externalIPs:
   - 192.168.0.22
